### ISSUE TITLE
Json

### ISSUE THREAD

**Issue by ancio** [ancio/GrupoAncioAleixoTesoura-#4]
Boa noite docente estamos a ter problemas de como extrar o json visto que ta tudo de uma forma ambigua, gostariamos da ajuda do docente.

**Comment by abdulmeque** [comment]
tudo em forma ambigua quer dizer uke?? como posso ajudar a resolver um problema assim? sem detalhes??? que tal ser mais mais explicito? incluir detalhes? screenshots??

**Comment by ancio** [comment]
![image](https://user-images.githubusercontent.com/42248445/47963617-66f5ad80-e037-11e8-97ea-5a1e8c71d7a2.png)

o http://emprego.sociomatico.com/wp-json/wp/v2 apresenta o json da pagina, entao nao estamos a conseguir extrair detalhes para enquadrar no aplicativo.

**Comment by abdulmeque** [comment]
Como assim?                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: ancioSent: Sunday, 4 November 2018 13:44To: ancio/GrupoAncioAleixoTesoura-Reply To: ancio/GrupoAncioAleixoTesoura-Cc: abdulmeque; CommentSubject: Re: [ancio/GrupoAncioAleixoTesoura-] Json (#4)
o http://emprego.sociomatico.com/wp-json/wp/v2 apresenta o json da pagina, entao nao estamos a conseguir extrair detalhes para enquadrar no aplicativo.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ancio/GrupoAncioAleixoTesoura-","title":"ancio/GrupoAncioAleixoTesoura-","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ancio/GrupoAncioAleixoTesoura-"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ancio in #4: ![image](https://user-images.githubusercontent.com/42248445/47963617-66f5ad80-e037-11e8-97ea-5a1e8c71d7a2.png)\r\n\r\no http://emprego.sociomatico.com/wp-json/wp/v2 apresenta o json da pagina, entao nao estamos a conseguir extrair detalhes para enquadrar no aplicativo.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/ancio/GrupoAncioAleixoTesoura-/issues/4#issuecomment-435662717"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ancio/GrupoAncioAleixoTesoura-/issues/4#issuecomment-435662717",
"url": "https://github.com/ancio/GrupoAncioAleixoTesoura-/issues/4#issuecomment-435662717",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [ancio/GrupoAncioAleixoTesoura-] Json (#4)",
"sections": [
{
"text": "",
"activityTitle": "**ancio**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ancio",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ancio/GrupoAncioAleixoTesoura-\",\n\"issueId\": 4,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ancio/GrupoAncioAleixoTesoura-\",\n\"issueId\": 4\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ancio/GrupoAncioAleixoTesoura-/issues/4#issuecomment-435662717"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 405929110\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by ancio** [comment]
Queriamos saber como podemos organizar para ligar com o aplicativo e que ja criamos as classes mas tamos a ter problemas pk o json como mostra ai na imagem esta desorganizado

**Comment by abdulmeque** [comment]
Não está organizado nada, o vosso problema é não fazer as coisas quando vos digo, eu vos disse para praticar e navegar essas API pra conhecerem bem mesmo, um mês atrás. Por exemplo, no dia que vos mostrei essas API, eu abri os json usando o Firefox. Isso não está desorganizado, voces é que não estudam. Procure na Google por editores JSON, copy esse json e mete num editor, aí irá conseguir ver a estrutura.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: ancioSent: Sunday, 4 November 2018 14:11To: ancio/GrupoAncioAleixoTesoura-Reply To: ancio/GrupoAncioAleixoTesoura-Cc: abdulmeque; CommentSubject: Re: [ancio/GrupoAncioAleixoTesoura-] Json (#4)Queriamos saber como podemos organizar para ligar com o aplicativo e que ja criamos as classes mas tamos a ter problemas pk o json como mostra ai na imagem esta desorganizado

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ancio/GrupoAncioAleixoTesoura-","title":"ancio/GrupoAncioAleixoTesoura-","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ancio/GrupoAncioAleixoTesoura-"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ancio in #4: Queriamos saber como podemos organizar para ligar com o aplicativo e que ja criamos as classes mas tamos a ter problemas pk o json como mostra ai na imagem esta desorganizado"}],"action":{"name":"View Issue","url":"https://github.com/ancio/GrupoAncioAleixoTesoura-/issues/4#issuecomment-435664424"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ancio/GrupoAncioAleixoTesoura-/issues/4#issuecomment-435664424",
"url": "https://github.com/ancio/GrupoAncioAleixoTesoura-/issues/4#issuecomment-435664424",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [ancio/GrupoAncioAleixoTesoura-] Json (#4)",
"sections": [
{
"text": "",
"activityTitle": "**ancio**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ancio",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ancio/GrupoAncioAleixoTesoura-\",\n\"issueId\": 4,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ancio/GrupoAncioAleixoTesoura-\",\n\"issueId\": 4\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ancio/GrupoAncioAleixoTesoura-/issues/4#issuecomment-435664424"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 405929110\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by ancio** [comment]
ok docente
